---
# This file contains variables that apply to all hosts in the inventory.

# The path to a YAML file containing VM definitions, potentially from a Puppet/Hiera setup.
# This is used by the 'kvm_setup' role to load VM data if 'cncloud::custom::vm_data' is not defined elsewhere.
custom_underlay_path: /etc/puppet/hiera/data/role/custom/custom-underlay.yaml
